//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageFusion.Resources.Strings;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppResources
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageFusion.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image Fusion.
    /// </summary>
    public static string ApplicationTitle => ResourceManager.GetString("ApplicationTitle", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Add.
    /// </summary>
    public static string ButtonAdd => ResourceManager.GetString("ButtonAdd", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Export.
    /// </summary>
    public static string ButtonExport => ResourceManager.GetString("ButtonExport", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Grid.
    /// </summary>
    public static string CombineTypeGrid => ResourceManager.GetString("CombineTypeGrid", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Horizontal.
    /// </summary>
    public static string CombineTypeHorizontal => ResourceManager.GetString("CombineTypeHorizontal", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Vertical.
    /// </summary>
    public static string CombineTypeVertical => ResourceManager.GetString("CombineTypeVertical", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to BMP.
    /// </summary>
    public static string ImageFormatBmp => ResourceManager.GetString("ImageFormatBmp", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to GIF.
    /// </summary>
    public static string ImageFormatGif => ResourceManager.GetString("ImageFormatGif", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to JPEG.
    /// </summary>
    public static string ImageFormatJpeg => ResourceManager.GetString("ImageFormatJpeg", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to PNG.
    /// </summary>
    public static string ImageFormatPng => ResourceManager.GetString("ImageFormatPng", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Select Combine Type.
    /// </summary>
    public static string PickerSelectCombineType => ResourceManager.GetString("PickerSelectCombineType", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Select Image Format.
    /// </summary>
    public static string PickerSelectImageFormat => ResourceManager.GetString("PickerSelectImageFormat", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Border.
    /// </summary>
    public static string SettingsBorder => ResourceManager.GetString("SettingsBorder", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Border Color.
    /// </summary>
    public static string SettingsBorderColor => ResourceManager.GetString("SettingsBorderColor", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Border Pixel.
    /// </summary>
    public static string SettingsBorderPixel => ResourceManager.GetString("SettingsBorderPixel", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Combine Type.
    /// </summary>
    public static string SettingsCombineType => ResourceManager.GetString("SettingsCombineType", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Height.
    /// </summary>
    public static string SettingsHeight => ResourceManager.GetString("SettingsHeight", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Image Dimensions.
    /// </summary>
    public static string SettingsImageDimensions => ResourceManager.GetString("SettingsImageDimensions", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Image Format.
    /// </summary>
    public static string SettingsImageFormat => ResourceManager.GetString("SettingsImageFormat", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Split.
    /// </summary>
    public static string SettingsSplit => ResourceManager.GetString("SettingsSplit", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Split Color.
    /// </summary>
    public static string SettingsSplitColor => ResourceManager.GetString("SettingsSplitColor", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Split Pixel.
    /// </summary>
    public static string SettingsSplitPixel => ResourceManager.GetString("SettingsSplitPixel", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Width.
    /// </summary>
    public static string SettingsWidth => ResourceManager.GetString("SettingsWidth", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Original.
    /// </summary>
    public static string TabOriginal => ResourceManager.GetString("TabOriginal", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Preview.
    /// </summary>
    public static string TabPreview => ResourceManager.GetString("TabPreview", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public static string TabSettings => ResourceManager.GetString("TabSettings", resourceCulture) ?? string.Empty;
}
